import React from 'react';
import { Story } from '@storybook/react/types-6-0';

import { SizeSelectorPopup } from './SizeSelectorPopup';
import { ISizeSelectorPopupProps } from './ISizeSelectorPopup';

export default {
  title: 'Size Selector Popup',
  component: SizeSelectorPopup,
};

const onSizeChartClick = () => {};
const Template: Story<ISizeSelectorPopupProps> = (args) => <SizeSelectorPopup {...args} />;
export const SizeSelectorPopupComponent = Template.bind({});

SizeSelectorPopupComponent.args = {
  showRfypCue: true,
  showAddToCart: true,
  selectedSku: {
    productName: 'Hello Applique Bow Formal Shirt and Pant Set 123',
    skuId: 'LTL-1989283',
    attributes: {
      accents: 'Embellished',
      character: 'Not applicable',
      colour: 'White',
      count: '1',
      'country of origin': 'ROW',
      embellishment: 'Foil',
      'fabric content': 'Cotton-blend',
      'fabric type': 'Jersey',
      hbt: 'H2',
      'hem length': 'Waist',
      neckline: 'Round Neck',
      occasion: 'piyush',
      season: 'Winter',
      size: '9-12 months',
      'sleeve length': 'Full Sleeves',
      stitch: 'Readymade',
      taste: 'City Look',
      'value pack': 'No',
      weave: 'Knit',
      year: '2019',
    },
    preorderAction: 'test',
    preorderInfo: 'test',
    shippingReturnInfoForSku: 'test',
    retailPrice: 799.0,
    regularPrice: 1049.0,
    availableQuantity: 10,
    saleType: 'PO',
    deliveryMsg: '4-5 days',
    rackStatus: 'Y',
    gender: "Boy's",
    discount: 24,
    isPresale: 0,
    canWishList: 1,
    maxDeliveryDays: 5,
    highlightEDD: 0,
    onSale: 1,
    finalSale: 0,
    fromAge: 6,
    toAge: 12,
    eddPrefix: 'Get it in ',
    eddColor: '#35b35d',
    eddTextColor: '#ffffff',
    isFastEdd: true,
    isInternationalPreorder: false,
    merchType: 'Catalog',
    deliveryMessage: {
      action: 'success',
      msg: '15 days return ',
      type: 1,
    },
  },
  simpleSkus: [
    {
      productName: 'Hello Applique Bow Formal Shirt and Pant Set 123',
      skuId: 'LTL-1989283',
      attributes: {
        accents: 'Embellished',
        character: 'Not applicable',
        colour: 'Red',
        count: '1',
        'country of origin': 'ROW',
        embellishment: 'Foil',
        'fabric content': 'Cotton-blend',
        'fabric type': 'Jersey',
        hbt: 'H2',
        'hem length': 'Waist',
        neckline: 'Round Neck',
        occasion: 'piyush',
        season: 'Winter',
        size: '1-2 years',
        'sleeve length': 'Full Sleeves',
        stitch: 'Readymade',
        taste: 'City Look',
        'value pack': 'No',
        weave: 'Knit',
        year: '2019',
      },
      preorderAction: 'test',
      preorderInfo: 'test',
      shippingReturnInfoForSku: 'test',
      retailPrice: 799.0,
      regularPrice: 1049.0,
      availableQuantity: 10,
      saleType: 'PO',
      deliveryMsg: '4-5 days',
      rackStatus: 'Y',
      gender: "Boy's",
      discount: 24,
      isPresale: 0,
      canWishList: 1,
      maxDeliveryDays: 5,
      highlightEDD: 0,
      onSale: 1,
      finalSale: 0,
      fromAge: 6,
      toAge: 12,
      eddPrefix: 'Get it in ',
      eddColor: '#35b35d',
      eddTextColor: '#ffffff',
      isFastEdd: true,
      isInternationalPreorder: false,
      merchType: 'Catalog',
      deliveryMessage: {
        action: 'success',
        msg: '15 days return ',
        type: 1,
      },
    },
    {
      productName: 'Hello Applique Bow Formal Shirt and Pant Set 123',
      skuId: 'LTL-1989284',
      attributes: {
        accents: 'Embellished',
        character: 'Not applicable',
        colour: 'White',
        count: '1',
        'country of origin': 'ROW',
        embellishment: 'Foil',
        'fabric content': 'Cotton-blend',
        'fabric type': 'Jersey',
        hbt: 'H2',
        'hem length': 'Waist',
        neckline: 'Round Neck',
        occasion: 'piyush',
        season: 'Winter',
        size: '9-12 months',
        'sleeve length': 'Full Sleeves',
        stitch: 'Readymade',
        taste: 'City Look',
        'value pack': 'No',
        weave: 'Knit',
        year: '2019',
      },
      preorderAction: 'test',
      preorderInfo: 'test',
      shippingReturnInfoForSku: 'test',
      retailPrice: 799.0,
      regularPrice: 1049.0,
      availableQuantity: 1,
      saleType: 'PO',
      deliveryMsg: '4-5 days',
      rackStatus: 'Y',
      gender: "Boy's",
      discount: 24,
      isPresale: 0,
      canWishList: 1,
      maxDeliveryDays: 5,
      highlightEDD: 0,
      onSale: 1,
      finalSale: 0,
      fromAge: 12,
      toAge: 24,
      eddPrefix: 'Get it in ',
      eddColor: '#35b35d',
      eddTextColor: '#ffffff',
      isFastEdd: true,
      isInternationalPreorder: false,
      merchType: 'Catalog',
      deliveryMessage: {
        action: 'success',
        msg: '15 days return ',
        type: 1,
      },
    },
    {
      productName: 'Hello Applique Bow Formal Shirt and Pant Set 123',
      skuId: 'LTL-1989285',
      attributes: {
        accents: 'Embellished',
        character: 'Not applicable',
        colour: 'Red',
        count: '1',
        'country of origin': 'ROW',
        embellishment: 'Foil',
        'fabric content': 'Cotton-blend',
        'fabric type': 'Jersey',
        hbt: 'H2',
        'hem length': 'Waist',
        neckline: 'Round Neck',
        occasion: 'piyush',
        season: 'Winter',
        size: '6-9 months',
        'sleeve length': 'Full Sleeves',
        stitch: 'Readymade',
        taste: 'City Look',
        'value pack': 'No',
        weave: 'Knit',
        year: '2019',
      },
      preorderAction: 'test',
      preorderInfo: 'test',
      shippingReturnInfoForSku: 'test',
      retailPrice: 799.0,
      regularPrice: 1049.0,
      availableQuantity: 10,
      saleType: 'PO',
      deliveryMsg: '4-5 days',
      rackStatus: 'Y',
      gender: "Boy's",
      discount: 24,
      isPresale: 0,
      canWishList: 1,
      maxDeliveryDays: 5,
      highlightEDD: 0,
      onSale: 1,
      finalSale: 0,
      fromAge: 24,
      toAge: 36,
      eddPrefix: 'Get it in ',
      eddColor: '#35b35d',
      eddTextColor: '#ffffff',
      isFastEdd: true,
      isInternationalPreorder: false,
      merchType: 'Catalog',
      deliveryMessage: {
        action: 'success',
        msg: '15 days return ',
        type: 1,
      },
    },
    {
      productName: 'Hello Applique Bow Formal Shirt and Pant Set 123',
      skuId: 'LTL-1989286',
      attributes: {
        size: '1-2 years',
      },
      retailPrice: 799.0,
      regularPrice: 1049.0,
      availableQuantity: 0,
      preorderAction: 'test',
      preorderInfo: 'test',
      shippingReturnInfoForSku: 'test',
      saleType: 'PO',
      deliveryMsg: '4-5 days',
      rackStatus: 'Y',
      gender: "Boy's",
      discount: 24,
      isPresale: 0,
      canWishList: 1,
      maxDeliveryDays: 5,
      highlightEDD: 0,
      onSale: 1,
      finalSale: 0,
      fromAge: 36,
      toAge: 48,
      eddPrefix: 'Get it in ',
      eddColor: '#35b35d',
      eddTextColor: '#ffffff',
      isFastEdd: true,
      isInternationalPreorder: false,
      merchType: 'Catalog',
      deliveryMessage: {
        action: 'success',
        msg: '15 days return ',
        type: 1,
      },
    },
  ],
  onSizeChartClick,
  goToProductRecommendation: onSizeChartClick,
};
