export * from './SvgIcon';
import ICCreate from './crm-icons/ic-create.svg';
import ICBack from './crm-icons/ic-white-back.svg';
import ICDashBoard from './crm-icons/ic-dashboard.svg';
import ICArchive from './crm-icons/ic-archive.svg';
import ICCloudUpload from './crm-icons/ic-cloud-upload.svg';
import ICSelectedCircle from './crm-icons/ic-selected-circle.svg';
import ICDeSelectedCircle from './crm-icons/ic-deselected-circle.svg';
import ICSelectedRectAngle from './crm-icons/ic-selected-rectangle.svg';
import ICDeSelectedRectAngle from './crm-icons/ic-deselected-rectangle.svg';
import ICFAQ from './crm-icons/ic-faq.svg';
import ICNonProc from './crm-icons/ic-non-proc.svg';
import ICTransfer from './crm-icons/ic-transfer.svg';
import HopScotch from './images/hopscotch.svg';
import ICCart from './images/ic-cart.svg';
export const CreateIcon = ICCreate;
export const BackIcon = ICBack;
export const DashBoardIcon = ICDashBoard;
export const ArchiveIcon = ICArchive;
export const UploadIcon = ICCloudUpload;
export const SelectedCircle = ICSelectedCircle;
export const DeSelectedCircle = ICDeSelectedCircle;
export const SelectedRectAngle = ICSelectedRectAngle;
export const DeSelectedRectAngle = ICDeSelectedRectAngle;
export const FAQIcon = ICFAQ;
export const NonProcIcon = ICNonProc;
export const TransferIcon = ICTransfer;
export const HopScotchIcon = HopScotch;
export const CartIcon = ICCart;
