export * from './SvgIcon';
import ICCreate from './crm-icons/ic-create.svg';
import ICBack from './crm-icons/ic-white-back.svg';
import ICDashBoard from './crm-icons/ic-dashboard.svg';
import ICArchive from './crm-icons/ic-archive.svg';
import ICCloudUpload from './crm-icons/ic-cloud-upload.svg';
import ICSelectedCircle from './crm-icons/ic-selected-circle.svg';
import ICDeSelectedCircle from './crm-icons/ic-deselected-circle.svg';
import ICSelectedRectAngle from './crm-icons/ic-selected-rectangle.svg';
import ICDeSelectedRectAngle from './crm-icons/ic-deselected-rectangle.svg';
import ICFAQ from './crm-icons/ic-faq.svg';
import ICNonProc from './crm-icons/ic-non-proc.svg';
import ICTransfer from './crm-icons/ic-transfer.svg';
import HopScotch from './images/hopscotch.svg';
import ICHsLogoPink from './footer-icons/hopscotch-pink.svg';
import ICCart from './images/ic-cart.svg';
import ICMailIcon from './footer-icons/mail-icon.svg';
import ICInfoIcon from './footer-icons/info-icon.svg';
import ICHsIcon from './footer-icons/hs-icon.svg';
import ICHsDarkIcon from './images/icon.hopscotch-dark.svg';
import ICHsThumbsup from './footer-icons/thumbsup-icon.svg';
import ICAppleIcon from './footer-icons/apple-icon.svg';
import ICPlayIcon from './footer-icons/play-icon.svg';
import ICFacebookIcon from './footer-icons/facebook-icon.svg';
import ICTwitterIcon from './footer-icons/twitter-icon.svg';
import ICInstagramIcon from './footer-icons/instagram-icon.svg';
import ICPIntrestIcon from './footer-icons/pinterest-icon.svg';
import ICIconClose from './images/icon-close.svg';
import ICIconWishList from './images/icon-wish-list.svg';
import ICIconWishListFilled from './images/ic-wish-filled.svg';
import ICIconTick from './images/icon-tick.svg';
import ICIconCrossRed from './images/icon-cross-red.svg';
import ICIconAngleDown from './images/icon-angle-down-v2.svg';
import ICIconSeeSimilar from './images/icon-see-similar.svg';
import ICIconSeeSimilarWhite from './images/icon-see-similar-white.svg';
import ICIconRadio from './images/ic-radio.svg';
import ICIconRadioActive from './images/ic-radio-active.svg';
import ICIconErrorMessage from './images/icon-error-msg.svg';
import ICIconSearch from './images/ic-seach-white.svg';
import ICIconWishListDefault from './images/ic-wish-default.svg';
import ICIconDropDown from './images/icon-dropdown.svg';
import ICIconDeliveryTruck from './images/ic-delivery-truck.svg';
import ICInfoBlackIcon from './images/icon-info-black.svg';
import ICChevronRightIcon from './images/chevron-right.svg';
import ICIconDismiss from './images/icon-dismiss.svg';

export const CreateIcon = ICCreate;
export const BackIcon = ICBack;
export const DashBoardIcon = ICDashBoard;
export const ArchiveIcon = ICArchive;
export const UploadIcon = ICCloudUpload;
export const SelectedCircle = ICSelectedCircle;
export const DeSelectedCircle = ICDeSelectedCircle;
export const SelectedRectAngle = ICSelectedRectAngle;
export const DeSelectedRectAngle = ICDeSelectedRectAngle;
export const FAQIcon = ICFAQ;
export const NonProcIcon = ICNonProc;
export const TransferIcon = ICTransfer;
export const HopScotchIcon = HopScotch;
export const CartIcon = ICCart;
export const MailIcon = ICMailIcon;
export const InfoIcon = ICInfoIcon;
export const HsIcon = ICHsIcon;
export const HsDarkIcon = ICHsDarkIcon;
export const HsLogoPink = ICHsLogoPink;
export const ThumbsupIcon = ICHsThumbsup;
export const AppleIcon = ICAppleIcon;
export const PlayIcon = ICPlayIcon;
export const FacebookIcon = ICFacebookIcon;
export const TwitterIcon = ICTwitterIcon;
export const InstagramIcon = ICInstagramIcon;
export const PIntrestIcon = ICPIntrestIcon;
export const IconClose = ICIconClose;
export const IconWishList = ICIconWishList;
export const IconWishListDefault = ICIconWishListDefault;
export const IconWishListFilled = ICIconWishListFilled;
export const IconTick = ICIconTick;
export const IconCrossRed = ICIconCrossRed;
export const IconAngleDown = ICIconAngleDown;
export const IconSeeSimilar = ICIconSeeSimilar;
export const IconSeeSimilarWhite = ICIconSeeSimilarWhite;
export const IconRadio = ICIconRadio;
export const IconRadioActive = ICIconRadioActive;
export const IconErrorMessage = ICIconErrorMessage;
export const IconSearch = ICIconSearch;
export const IconDropDown = ICIconDropDown;
export const IconDeliveryTruck = ICIconDeliveryTruck;
export const IconInfoBlack = ICInfoBlackIcon;
export const IconChevronRight = ICChevronRightIcon;
export const IconDismiss = ICIconDismiss;
