import React from 'react';
import { Story } from '@storybook/react/types-6-0';

import { Accordion } from './Accordion';
import { IAccordionProps } from '../IAccordion';

export default {
  title: 'Accordian',
  component: Accordion,
};

const Template: Story<IAccordionProps> = (args) => <Accordion {...args} />;
export const AccordionComponent = Template.bind({});

AccordionComponent.args = {};

// AccordianComponent.args = {
//   productData: {
//     isReturnable: 1,
//     subProductTypeId: 2112,
//     subProductTypeName: 'Testing001',
//     action: 'success',
//     id: 947821,
//     productDesc:
//       '<b>FEATURES:</b><ul style="margin-bottom: 10px;"><li>Material: 80% Cotton,20% Fiber&nbsp;</li><li>The actual product may differ slightly in color from the one illustrated in the images..<br></li></ul><b>WHAT\'S INCLUDED:</b><ul><li>1 Leggings</li></ul><b>CARE:</b><ul><li>Gentle Wash</li></ul>',
//     simpleSkus: [
//       {
//         productName: 'Black Stripes Elasticated Leggings',
//         skuId: 'LSM-3057058',
//         attrs: [
//           { name: 'Colour', value: 'Black' },
//           { name: 'From Age', value: '48' },
//           { name: 'Gender', value: "Girl's" },
//           { name: 'HBT', value: 'B2' },
//           { name: 'Season', value: 'All' },
//           { name: 'Size', value: '4-5 years' },
//           { name: 'Colour', value: 'Black' },
//           { name: 'To Age', value: '60' },
//           { name: 'Year', value: '2020' },
//         ],
//         retailPrice: 727,
//         regularPrice: 889,
//         availableQuantity: 0,
//         saleType: 'PO',
//         deliveryMsg: '4-5 weeks',
//         rackStatus: 'Y',
//         gender: "Girl's",
//         discount: 18,
//         isPresale: 0,
//         canWishList: 0,
//         maxDeliveryDays: 31,
//         highlightEDD: 0,
//         onSale: 0,
//         finalSale: 0,
//         fromAge: 48,
//         toAge: 60,
//         eddPrefix: 'Get it in ',
//         eddColor: '#ffcc33',
//         eddTextColor: '#333333',
//         isFastEdd: false,
//         isInternationalPreorder: false,
//         merchType: 'Catalog',
//         deliveryMessage: { action: 'success', msg: '15 days return ', type: 1 },
//       },
//       {
//         productName: 'Black Stripes Elasticated Leggings',
//         skuId: 'LSM-3057059',
//         attrs: [
//           { name: 'Colour', value: 'Black' },
//           { name: 'From Age', value: '72' },
//           { name: 'Gender', value: "Girl's" },
//           { name: 'HBT', value: 'B2' },
//           { name: 'Season', value: 'All' },
//           { name: 'Size', value: '6-7 years' },
//           { name: 'Colour', value: 'Black' },
//           { name: 'To Age', value: '84' },
//           { name: 'Year', value: '2020' },
//         ],
//         retailPrice: 727,
//         regularPrice: 889,
//         availableQuantity: 0,
//         saleType: 'PO',
//         deliveryMsg: '4-5 weeks',
//         rackStatus: 'Y',
//         gender: "Girl's",
//         discount: 18,
//         isPresale: 0,
//         canWishList: 0,
//         maxDeliveryDays: 31,
//         highlightEDD: 0,
//         onSale: 0,
//         finalSale: 0,
//         fromAge: 72,
//         toAge: 84,
//         eddPrefix: 'Get it in ',
//         eddColor: '#ffcc33',
//         eddTextColor: '#333333',
//         isFastEdd: false,
//         isInternationalPreorder: false,
//         merchType: 'Catalog',
//         deliveryMessage: { action: 'success', msg: '15 days return ', type: 1 },
//       },
//       {
//         productName: 'Black Stripes Elasticated Leggings',
//         skuId: 'LSM-3057060',
//         attrs: [
//           { name: 'Colour', value: 'Black' },
//           { name: 'From Age', value: '84' },
//           { name: 'Gender', value: "Girl's" },
//           { name: 'HBT', value: 'B2' },
//           { name: 'Season', value: 'All' },
//           { name: 'Size', value: '7-8 years' },
//           { name: 'Colour', value: 'Black' },
//           { name: 'To Age', value: '96' },
//           { name: 'Year', value: '2020' },
//         ],
//         retailPrice: 727,
//         regularPrice: 889,
//         availableQuantity: 0,
//         saleType: 'PO',
//         deliveryMsg: '4-5 weeks',
//         rackStatus: 'Y',
//         gender: "Girl's",
//         discount: 18,
//         isPresale: 0,
//         canWishList: 0,
//         maxDeliveryDays: 31,
//         highlightEDD: 0,
//         onSale: 0,
//         finalSale: 0,
//         fromAge: 84,
//         toAge: 96,
//         eddPrefix: 'Get it in ',
//         eddColor: '#ffcc33',
//         eddTextColor: '#333333',
//         isFastEdd: false,
//         isInternationalPreorder: false,
//         merchType: 'Catalog',
//         deliveryMessage: { action: 'success', msg: '15 days return ', type: 1 },
//       },
//       {
//         productName: 'Black Stripes Elasticated Leggings',
//         skuId: 'LSM-3057061',
//         attrs: [
//           { name: 'Colour', value: 'Black' },
//           { name: 'From Age', value: '96' },
//           { name: 'Gender', value: "Girl's" },
//           { name: 'HBT', value: 'B2' },
//           { name: 'Season', value: 'All' },
//           { name: 'Size', value: '8-9 years' },
//           { name: 'Colour', value: 'Black' },
//           { name: 'To Age', value: '108' },
//           { name: 'Year', value: '2020' },
//         ],
//         retailPrice: 727,
//         regularPrice: 889,
//         availableQuantity: 0,
//         saleType: 'PO',
//         deliveryMsg: '4-5 weeks',
//         rackStatus: 'Y',
//         gender: "Girl's",
//         discount: 18,
//         isPresale: 0,
//         canWishList: 0,
//         maxDeliveryDays: 31,
//         highlightEDD: 0,
//         onSale: 0,
//         finalSale: 0,
//         fromAge: 96,
//         toAge: 108,
//         eddPrefix: 'Get it in ',
//         eddColor: '#ffcc33',
//         eddTextColor: '#333333',
//         isFastEdd: false,
//         isInternationalPreorder: false,
//         merchType: 'Catalog',
//         deliveryMessage: { action: 'success', msg: '15 days return ', type: 1 },
//       },
//       {
//         productName: 'Black Stripes Elasticated Leggings',
//         skuId: 'LSM-3057062',
//         attrs: [
//           { name: 'Colour', value: 'Black' },
//           { name: 'From Age', value: '120' },
//           { name: 'Gender', value: "Girl's" },
//           { name: 'HBT', value: 'B2' },
//           { name: 'Season', value: 'All' },
//           { name: 'Size', value: '10-11 years' },
//           { name: 'Colour', value: 'Black' },
//           { name: 'To Age', value: '132' },
//           { name: 'Year', value: '2020' },
//         ],
//         retailPrice: 727,
//         regularPrice: 889,
//         availableQuantity: 0,
//         saleType: 'PO',
//         deliveryMsg: '5-6 weeks',
//         rackStatus: 'Y',
//         gender: "Girl's",
//         discount: 18,
//         isPresale: 1,
//         canWishList: 0,
//         maxDeliveryDays: 39,
//         highlightEDD: 0,
//         onSale: 0,
//         finalSale: 0,
//         fromAge: 120,
//         toAge: 132,
//         eddPrefix: 'Get it in ',
//         eddColor: '#ffcc33',
//         eddTextColor: '#333333',
//         isFastEdd: false,
//         isInternationalPreorder: true,
//         preorderAction: '/collections/preorder',
//         preorderInfo: 'Why the wait?',
//         merchType: 'Catalog',
//         deliveryMessage: { action: 'success', msg: '15 days return ', type: 1 },
//       },
//     ],
//     imgurls: [
//       {
//         imgUrl:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/6f23ef40-8e61-43fe-85a9-9b44e405bf6e_medium.jpg?version=1593498624629',
//         imgUrlLarge:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/6f23ef40-8e61-43fe-85a9-9b44e405bf6e_large.jpg?version=1593498624629',
//         imgUrlFull:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/6f23ef40-8e61-43fe-85a9-9b44e405bf6e_full.jpg?version=1593498624629',
//         imgUrlThumbnail:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/6f23ef40-8e61-43fe-85a9-9b44e405bf6e_thumbnail.jpg?version=1593498624629',
//         isCover: true,
//         imgUrlHeight: 360,
//         imgUrlWidth: 360,
//         imgUrlLargeHeight: 600,
//         imgUrlLargeWidth: 600,
//         imgUrlFullHeight: 1000,
//         imgUrlFullWidth: 1000,
//         imgUrlThumbnailHeight: 70,
//         imgUrlThumbnailWidth: 70,
//       },
//       {
//         imgUrl:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/8cfd6674-9e71-4244-a755-7fd79d0562e0_medium.jpg?version=1593498626330',
//         imgUrlLarge:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/8cfd6674-9e71-4244-a755-7fd79d0562e0_large.jpg?version=1593498626330',
//         imgUrlFull:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/8cfd6674-9e71-4244-a755-7fd79d0562e0_full.jpg?version=1593498626330',
//         imgUrlThumbnail:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/8cfd6674-9e71-4244-a755-7fd79d0562e0_thumbnail.jpg?version=1593498626330',
//         isCover: false,
//         imgUrlHeight: 360,
//         imgUrlWidth: 360,
//         imgUrlLargeHeight: 600,
//         imgUrlLargeWidth: 600,
//         imgUrlFullHeight: 1000,
//         imgUrlFullWidth: 1000,
//         imgUrlThumbnailHeight: 70,
//         imgUrlThumbnailWidth: 70,
//       },
//       {
//         imgUrl:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/dc38e90e-94e5-4c66-9892-ac37e14f489c_medium.jpg?version=1593498627943',
//         imgUrlLarge:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/dc38e90e-94e5-4c66-9892-ac37e14f489c_large.jpg?version=1593498627943',
//         imgUrlFull:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/dc38e90e-94e5-4c66-9892-ac37e14f489c_full.jpg?version=1593498627943',
//         imgUrlThumbnail:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/dc38e90e-94e5-4c66-9892-ac37e14f489c_thumbnail.jpg?version=1593498627943',
//         isCover: false,
//         imgUrlHeight: 360,
//         imgUrlWidth: 360,
//         imgUrlLargeHeight: 600,
//         imgUrlLargeWidth: 600,
//         imgUrlFullHeight: 1000,
//         imgUrlFullWidth: 1000,
//         imgUrlThumbnailHeight: 70,
//         imgUrlThumbnailWidth: 70,
//       },
//       {
//         imgUrl:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/aae65a9d-7e1b-492f-94ac-db5c882028a4_medium.jpg?version=1593498629562',
//         imgUrlLarge:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/aae65a9d-7e1b-492f-94ac-db5c882028a4_large.jpg?version=1593498629562',
//         imgUrlFull:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/aae65a9d-7e1b-492f-94ac-db5c882028a4_full.jpg?version=1593498629562',
//         imgUrlThumbnail:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/aae65a9d-7e1b-492f-94ac-db5c882028a4_thumbnail.jpg?version=1593498629562',
//         isCover: false,
//         imgUrlHeight: 360,
//         imgUrlWidth: 360,
//         imgUrlLargeHeight: 600,
//         imgUrlLargeWidth: 600,
//         imgUrlFullHeight: 1000,
//         imgUrlFullWidth: 1000,
//         imgUrlThumbnailHeight: 70,
//         imgUrlThumbnailWidth: 70,
//       },
//       {
//         imgUrl:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/24acf405-ce71-4010-b772-9883ea70c977_medium.jpg?version=1593498631122',
//         imgUrlLarge:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/24acf405-ce71-4010-b772-9883ea70c977_large.jpg?version=1593498631122',
//         imgUrlFull:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/24acf405-ce71-4010-b772-9883ea70c977_full.jpg?version=1593498631122',
//         imgUrlThumbnail:
//           'https://qastatic.hopscotch.in/fstatic/product/202006/24acf405-ce71-4010-b772-9883ea70c977_thumbnail.jpg?version=1593498631122',
//         isCover: false,
//         imgUrlHeight: 360,
//         imgUrlWidth: 360,
//         imgUrlLargeHeight: 600,
//         imgUrlLargeWidth: 600,
//         imgUrlFullHeight: 1000,
//         imgUrlFullWidth: 1000,
//         imgUrlThumbnailHeight: 70,
//         imgUrlThumbnailWidth: 70,
//       },
//     ],
//     brandName: 'LSM',
//     hasSizeChart: true,
//     quantity: 0,
//     shippingReturnInfo:
//       "<p>Free shipping on orders above ₹1,500. Only ships in India.<br/>Most items are eligible for returns (within 15 days of delivery). However, innerwear (including lingerie) swimwear, jewelry, consumable goods and 'final sale' items are not eligible for returns. Please see our detailed <a href='http://www.qa.hopscotch.in/help#returns' target='_blank'>return policy</a>.</p>",
//     canWishList: 0,
//     restTime: 0,
//     preOrderDescription:
//       'Pre-ordering items on Hopscotch allows you to book select international products ahead of time. This system allows us to offer you a wider range of products at competitive prices. Pre-order products generally take 4-6 weeks to be delivered.',
//     productLevelAttrList: [
//       {
//         attributeName: 'Features',
//         isShowAttr: false,
//         productSubAttrList: [
//           { subAttributeName: 'SubFeature_1', isShowAttrName: false },
//           { subAttributeName: 'SubFeature_2', isShowAttrName: false },
//           { subAttributeName: 'SubFeature_3', isShowAttrName: false },
//           { subAttributeName: 'SubFeature_4', isShowAttrName: false },
//           { subAttributeName: 'SubFeature_5', isShowAttrName: false },
//           { subAttributeName: 'SubFeature_6', isShowAttrName: false },
//           { subAttributeName: 'SubFeature_7', isShowAttrName: false },
//           { subAttributeName: 'SubFeature_8', isShowAttrName: false },
//           { subAttributeName: 'SubFeature_9', isShowAttrName: false },
//         ],
//       },
//       {
//         attributeName: "What's included",
//         isShowAttr: false,
//         productSubAttrList: [
//           { subAttributeName: 'SubInculde_1', isShowAttrName: false },
//           { subAttributeName: 'SubInculde_2', isShowAttrName: false },
//           { subAttributeName: 'SubInculde_3', isShowAttrName: false },
//           { subAttributeName: 'SubInculde_4', isShowAttrName: false },
//           { subAttributeName: 'SubInculde_5', isShowAttrName: false },
//           { subAttributeName: 'SubInculde_6', isShowAttrName: false },
//           { subAttributeName: 'SubInculde_7', isShowAttrName: false },
//           { subAttributeName: 'SubInculde_8', isShowAttrName: false },
//         ],
//       },
//       {
//         attributeName: 'Book Details',
//         isShowAttr: false,
//         productSubAttrList: [
//           { subAttributeName: 'Author', isShowAttrName: true },
//           { subAttributeName: 'Binding type', isShowAttrName: true },
//           { subAttributeName: 'Language', isShowAttrName: true },
//           { subAttributeName: 'Publisher', isShowAttrName: true },
//           { subAttributeName: 'Number of pages', isShowAttrName: true },
//           { subAttributeName: 'Publication year', isShowAttrName: true },
//         ],
//       },
//       { attributeName: 'Fabric', attributeValue: '', isShowAttr: false },
//       { attributeName: 'Material', isShowAttr: false },
//       {
//         attributeName: 'Care',
//         isShowAttr: false,
//         productSubAttrList: [
//           { subAttributeName: 'SubCare_1', isShowAttrName: false },
//           { subAttributeName: 'SubCare_2', isShowAttrName: false },
//           { subAttributeName: 'SubCare_3', isShowAttrName: false },
//           { subAttributeName: 'SubCare_4', isShowAttrName: false },
//           { subAttributeName: 'SubCare_5', isShowAttrName: false },
//         ],
//       },
//       { attributeName: 'Important Note', isShowAttr: false },
//       { attributeName: 'Warning', isShowAttr: false },
//       { attributeName: 'Warranty', isShowAttr: false },
//       { attributeName: 'GBYR', isShowAttr: false },
//       { attributeName: 'Hopscotch_brand', isShowAttr: false },
//     ],
//     categoryId: 373,
//     subCategoryId: 426,
//     productTypeId: 108,
//     canPreSale: 1,
//     isPresale: 0,
//     maxDeliveryDays: 0,
//     highlightEDD: 0,
//     categoryName: 'Apparel - Children',
//     subcategoryName: "Bottoms!@#$%^&*1909';",
//     productTypeName: 'Leggings',
//     onSale: 0,
//     fromAge: 48,
//     toAge: 132,
//     deliveryMessages: [
//       { action: 'success', msg: '15 days return ', type: 1 },
//       { action: 'success', msg: 'This product is Non-exchangeable', type: 0 },
//     ],
//     showProductDetails: true,
//     showBrandDetails: false,
//     showPreOrderInfo: false,
//     showShippingInfo: false,
//     showPincodeBasedEdd: false,
//     retailPrice: 727,
//     eddPrefix: 'Get it in ',
//     eddColor: '#35b35d',
//     eddTextColor: '#ffffff',
//     serviceable: true,
//     isInternationalPreorder: false,
//     country: 'Rest',
//     isEddDifferentForSKUs: true,
//     isReturnInfoDifferentForSKUs: false,
//     showSizePickerDropdown: true,
//     sizePickerDropdownLabel: 'Select a size for delivery information',
//     brandId: 15920,
//     isWishlisted: false,
//     showRfypCue: true,
//     isDefault: false,
//     isfirst: false,
//     isProductSoldOut: true,
//   },
//   sku: {
//     shippingReturnInfoForSku: 'Test it out',
//   },
// };
