import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { NavBar } from '@hs/components';

const Product: NextPage = () => {
  const router = useRouter();
  const { productId } = router.query;
  return (
    <div>
      <Head>
        <title>Product details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <NavBar></NavBar>
        <p>Product Id: {productId}</p>
      </main>
    </div>
  );
};

export default Product;
