import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';

const Product: NextPage = () => {
  const router = useRouter();
  const { productId } = router.query;
  return (
    <div className={styles.container}>
      <Head>
        <title>Product details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>Products page</p>
        <p className={styles.description}>Product Id: {productId}</p>
      </main>
    </div>
  );
};

export default Product;
